
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Packages (Python)
    command: 'pip install -r requirements.txt'
  - name: Create Database
    command: 'mysql -u root -p -e "create database researchprojectdb"'
  - name: Load SQL into Database
    command: 'mysql -u root -D researchprojectdb < ./researchprojectdb.sql'
vscode:
  extensions:
    - ms-python.python
    - samuelcolvin.jinjahtml
